// Generated by Lasy AI - https://lasy.ai
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
// Import all available fonts for AI usage
import "../lib/fonts";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Assistente de Saúde IA",
  description: "Seu assistente pessoal de saúde com inteligência artificial",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <Script src="/lasy-bridge.js" strategy="beforeInteractive" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} min-h-screen bg-gradient-to-br from-blue-50 via-white to-cyan-50 antialiased relative overflow-x-hidden`}
      >
        {/* Bolinhas caindo no background */}
        <div className="fixed inset-0 pointer-events-none z-0 overflow-hidden">
          {/* Camada 1 - Bolinhas grandes */}
          {[...Array(15)].map((_, i) => (
            <div
              key={`bubble-large-${i}`}
              className="absolute rounded-full bg-gradient-to-br from-blue-400/20 to-cyan-400/20 backdrop-blur-sm animate-float"
              style={{
                width: `${Math.random() * 80 + 40}px`,
                height: `${Math.random() * 80 + 40}px`,
                left: `${Math.random() * 100}%`,
                top: `-${Math.random() * 100}px`,
                animationDelay: `${Math.random() * 5}s`,
                animationDuration: `${Math.random() * 10 + 15}s`,
              }}
            />
          ))}
          
          {/* Camada 2 - Bolinhas médias */}
          {[...Array(25)].map((_, i) => (
            <div
              key={`bubble-medium-${i}`}
              className="absolute rounded-full bg-gradient-to-br from-purple-400/15 to-pink-400/15 backdrop-blur-sm animate-float"
              style={{
                width: `${Math.random() * 50 + 20}px`,
                height: `${Math.random() * 50 + 20}px`,
                left: `${Math.random() * 100}%`,
                top: `-${Math.random() * 150}px`,
                animationDelay: `${Math.random() * 7}s`,
                animationDuration: `${Math.random() * 12 + 18}s`,
              }}
            />
          ))}
          
          {/* Camada 3 - Bolinhas pequenas */}
          {[...Array(40)].map((_, i) => (
            <div
              key={`bubble-small-${i}`}
              className="absolute rounded-full bg-gradient-to-br from-teal-400/10 to-emerald-400/10 backdrop-blur-sm animate-float"
              style={{
                width: `${Math.random() * 30 + 10}px`,
                height: `${Math.random() * 30 + 10}px`,
                left: `${Math.random() * 100}%`,
                top: `-${Math.random() * 200}px`,
                animationDelay: `${Math.random() * 10}s`,
                animationDuration: `${Math.random() * 15 + 20}s`,
              }}
            />
          ))}
        </div>
        
        {/* Conteúdo principal */}
        <div className="relative z-10">
          {children}
        </div>
      </body>
    </html>
  );
}
